// 布局通用部件统一出口：供各布局模板从同一处按需引入，新增部件在此补一行即可被各布局使用
export { default as BeginnerGuide } from './BeginnerGuide.vue'
export { default as BreadCrumb } from './BreadCrumb.vue'
export { default as Fullscreen } from './Fullscreen.vue'
export { default as MenuCollapse } from './MenuCollapse.vue'
export { default as RoleSelect } from './RoleSelect.vue'
export { default as SideLogo } from './SideLogo.vue'
export { default as SideMenu } from './SideMenu.vue'
export { default as AppTab } from './tab/index.vue'
export { default as UserAvatar } from './UserAvatar.vue'
